/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf --types 
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/commodore-64-computer-3da4b1bade284fdb94d34573e9ff7002
Title: Commodore 64 || Computer
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
	nodes: {
		Object_4: THREE.Mesh
		Object_6: THREE.Mesh
		Object_8: THREE.Mesh
		Object_10: THREE.Mesh
		Object_12: THREE.Mesh
		Object_14: THREE.Mesh
		Object_16: THREE.Mesh
		Object_18: THREE.Mesh
		Object_20: THREE.Mesh
		Object_22: THREE.Mesh
		Object_24: THREE.Mesh
		Object_26: THREE.Mesh
		Object_28: THREE.Mesh
		Object_30: THREE.Mesh
		Object_32: THREE.Mesh
		Object_34: THREE.Mesh
		Object_36: THREE.Mesh
		Object_38: THREE.Mesh
		Object_40: THREE.Mesh
		Object_42: THREE.Mesh
		Object_44: THREE.Mesh
		Object_46: THREE.Mesh
		Object_48: THREE.Mesh
		Object_50: THREE.Mesh
		Object_52: THREE.Mesh
		Object_54: THREE.Mesh
		Object_56: THREE.Mesh
		Object_58: THREE.Mesh
		Object_60: THREE.Mesh
		Object_62: THREE.Mesh
		Object_64: THREE.Mesh
		Object_66: THREE.Mesh
		Object_68: THREE.Mesh
		Object_70: THREE.Mesh
		Object_72: THREE.Mesh
		Object_74: THREE.Mesh
		Object_76: THREE.Mesh
		Object_78: THREE.Mesh
		Object_80: THREE.Mesh
		Object_82: THREE.Mesh
		Object_84: THREE.Mesh
		Object_86: THREE.Mesh
		Object_88: THREE.Mesh
		Object_90: THREE.Mesh
		Object_92: THREE.Mesh
		Object_94: THREE.Mesh
		Object_96: THREE.Mesh
		Object_98: THREE.Mesh
		Object_100: THREE.Mesh
		Object_102: THREE.Mesh
		Object_104: THREE.Mesh
		Object_106: THREE.Mesh
		Object_108: THREE.Mesh
		Object_110: THREE.Mesh
		Object_112: THREE.Mesh
		Object_114: THREE.Mesh
		Object_116: THREE.Mesh
		Object_118: THREE.Mesh
		Object_120: THREE.Mesh
		Object_122: THREE.Mesh
		Object_124: THREE.Mesh
		Object_126: THREE.Mesh
		Object_128: THREE.Mesh
		Object_130: THREE.Mesh
		Object_132: THREE.Mesh
		Object_134: THREE.Mesh
		Object_136: THREE.Mesh
		Object_138: THREE.Mesh
		Object_140: THREE.Mesh
		Object_142: THREE.Mesh
		Object_144: THREE.Mesh
		Object_146: THREE.Mesh
		Object_148: THREE.Mesh
		Object_150: THREE.Mesh
		Object_152: THREE.Mesh
		Object_154: THREE.Mesh
		Object_156: THREE.Mesh
		Object_158: THREE.Mesh
		Object_160: THREE.Mesh
		Object_162: THREE.Mesh
		Object_164: THREE.Mesh
		Object_166: THREE.Mesh
		Object_168: THREE.Mesh
		Object_170: THREE.Mesh
		Object_172: THREE.Mesh
		Object_174: THREE.Mesh
		Object_176: THREE.Mesh
		Object_178: THREE.Mesh
		Object_180: THREE.Mesh
		Object_182: THREE.Mesh
		Object_184: THREE.Mesh
		Object_186: THREE.Mesh
		Object_188: THREE.Mesh
		Object_190: THREE.Mesh
		Object_192: THREE.Mesh
		Object_194: THREE.Mesh
		Object_196: THREE.Mesh
		Object_198: THREE.Mesh
		Object_200: THREE.Mesh
		Object_202: THREE.Mesh
		Object_204: THREE.Mesh
		Object_206: THREE.Mesh
		Object_208: THREE.Mesh
		Object_210: THREE.Mesh
		Object_212: THREE.Mesh
		Object_214: THREE.Mesh
		Object_216: THREE.Mesh
		Object_218: THREE.Mesh
		Object_220: THREE.Mesh
		Object_222: THREE.Mesh
		Object_224: THREE.Mesh
		Object_226: THREE.Mesh
		Object_228: THREE.Mesh
		Object_230: THREE.Mesh
		Object_232: THREE.Mesh
		Object_234: THREE.Mesh
		Object_236: THREE.Mesh
		Object_238: THREE.Mesh
		Object_240: THREE.Mesh
		Object_242: THREE.Mesh
		Object_244: THREE.Mesh
		Object_246: THREE.Mesh
		Object_248: THREE.Mesh
		Object_250: THREE.Mesh
		Object_252: THREE.Mesh
		Object_254: THREE.Mesh
		Object_256: THREE.Mesh
		Object_258: THREE.Mesh
		Object_260: THREE.Mesh
		Object_262: THREE.Mesh
		Object_264: THREE.Mesh
		Object_266: THREE.Mesh
		Object_268: THREE.Mesh
		Object_270: THREE.Mesh
		Object_272: THREE.Mesh
		Object_274: THREE.Mesh
		Object_276: THREE.Mesh
		Object_278: THREE.Mesh
		Object_280: THREE.Mesh
		Object_282: THREE.Mesh
		Object_284: THREE.Mesh
		Object_286: THREE.Mesh
		Object_288: THREE.Mesh
		Object_290: THREE.Mesh
		Object_292: THREE.Mesh
		Object_294: THREE.Mesh
		Object_296: THREE.Mesh
		Object_298: THREE.Mesh
		Object_300: THREE.Mesh
		Object_302: THREE.Mesh
		Object_304: THREE.Mesh
		Object_306: THREE.Mesh
		Object_308: THREE.Mesh
		Object_310: THREE.Mesh
		Object_312: THREE.Mesh
		Object_314: THREE.Mesh
		Object_316: THREE.Mesh
		Object_318: THREE.Mesh
		Object_320: THREE.Mesh
		Object_322: THREE.Mesh
		Object_324: THREE.Mesh
		Object_326: THREE.Mesh
		Object_328: THREE.Mesh
		Object_330: THREE.Mesh
		Object_332: THREE.Mesh
		Object_334: THREE.Mesh
		Object_336: THREE.Mesh
		Object_338: THREE.Mesh
		Object_340: THREE.Mesh
		Object_342: THREE.Mesh
		Object_344: THREE.Mesh
		Object_346: THREE.Mesh
		Object_348: THREE.Mesh
		Object_350: THREE.Mesh
		Object_352: THREE.Mesh
		Object_354: THREE.Mesh
		Object_356: THREE.Mesh
		Object_358: THREE.Mesh
		Object_360: THREE.Mesh
		Object_362: THREE.Mesh
		Object_364: THREE.Mesh
		Object_366: THREE.Mesh
		Object_368: THREE.Mesh
		Object_370: THREE.Mesh
		Object_372: THREE.Mesh
		Object_374: THREE.Mesh
		Object_376: THREE.Mesh
		Object_378: THREE.Mesh
		Object_380: THREE.Mesh
		Object_382: THREE.Mesh
		Object_384: THREE.Mesh
		Object_386: THREE.Mesh
		Object_388: THREE.Mesh
		Object_390: THREE.Mesh
		Object_392: THREE.Mesh
		Object_394: THREE.Mesh
		Object_396: THREE.Mesh
		Object_398: THREE.Mesh
		Object_400: THREE.Mesh
		Object_402: THREE.Mesh
		Object_404: THREE.Mesh
		Object_406: THREE.Mesh
		Object_408: THREE.Mesh
		Object_410: THREE.Mesh
		Object_412: THREE.Mesh
		Object_414: THREE.Mesh
		Object_416: THREE.Mesh
		Object_418: THREE.Mesh
		Object_420: THREE.Mesh
		Object_422: THREE.Mesh
	}
	materials: {
		details: THREE.MeshStandardMaterial
		keyboard: THREE.MeshStandardMaterial
		main_body: THREE.MeshPhysicalMaterial
	}
	animations: any
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult

	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_4.geometry}
				material={materials.details}
				position={[1.117, -0.101, -0.933]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_6.geometry}
				material={materials.details}
				position={[2.141, -0.305, 1.026]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_8.geometry}
				material={materials.details}
				position={[1.734, -0.101, -0.933]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_10.geometry}
				material={materials.details}
				position={[-1.308, -0.101, -0.867]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_12.geometry}
				material={materials.details}
				position={[-0.692, -0.101, -0.867]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_14.geometry}
				material={materials.details}
				position={[-2.255, -0.101, -0.867]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_16.geometry}
				material={materials.details}
				position={[-1.738, -0.101, -0.867]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_18.geometry}
				material={materials.details}
				position={[-1.308, -0.101, -0.6]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_20.geometry}
				material={materials.details}
				position={[-0.692, -0.101, -0.6]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_22.geometry}
				material={materials.details}
				position={[-2.255, -0.101, -0.6]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_24.geometry}
				material={materials.details}
				position={[-1.738, -0.101, -0.6]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_26.geometry}
				material={materials.details}
				position={[-0.702, -0.274, -0.903]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_28.geometry}
				material={materials.details}
				position={[-0.702, -0.274, -0.686]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_30.geometry}
				material={materials.details}
				position={[-1.31, -0.274, -0.903]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_32.geometry}
				material={materials.details}
				position={[-1.31, -0.274, -0.686]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_34.geometry}
				material={materials.details}
				position={[-2.229, -0.274, -0.903]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_36.geometry}
				material={materials.details}
				position={[-2.229, -0.274, -0.686]}
				rotation={[-Math.PI, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_38.geometry}
				material={materials.details}
				position={[0.003, -0.305, 1.026]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_40.geometry}
				material={materials.details}
				position={[-2.166, -0.305, 1.026]}
				rotation={[0, 0, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_42.geometry}
				material={materials.details}
				position={[-0.702, -0.329, -0.687]}
			/>
			<mesh
				geometry={nodes.Object_44.geometry}
				material={materials.details}
				position={[-2.228, -0.329, -0.903]}
			/>
			<mesh
				geometry={nodes.Object_46.geometry}
				material={materials.details}
				position={[-1.31, -0.329, -0.903]}
			/>
			<mesh
				geometry={nodes.Object_48.geometry}
				material={materials.details}
				position={[-0.702, -0.329, -0.903]}
			/>
			<mesh
				geometry={nodes.Object_50.geometry}
				material={materials.details}
				position={[-2.228, -0.329, -0.687]}
			/>
			<mesh
				geometry={nodes.Object_52.geometry}
				material={materials.details}
				position={[-1.31, -0.329, -0.687]}
			/>
			<mesh
				geometry={nodes.Object_54.geometry}
				material={materials.details}
				position={[1.119, -0.355, -0.903]}
			/>
			<mesh
				geometry={nodes.Object_56.geometry}
				material={materials.details}
				position={[1.727, -0.355, -0.903]}
			/>
			<mesh
				geometry={nodes.Object_58.geometry}
				material={materials.details}
				position={[0.714, -0.154, -1.095]}
				rotation={[-Math.PI / 2, Math.PI / 4, 0]}
			/>
			<mesh
				geometry={nodes.Object_60.geometry}
				material={materials.details}
				position={[0.431, -0.154, -1.095]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_62.geometry}
				material={materials.details}
				position={[2.284, -0.188, -0.791]}
			/>
			<mesh
				geometry={nodes.Object_64.geometry}
				material={materials.details}
				position={[-0.371, -0.17, -1.076]}
				rotation={[0, Math.PI / 2, 0]}
			/>
			<mesh
				geometry={nodes.Object_66.geometry}
				material={materials.details}
				position={[-0.059, -0.17, -1.076]}
				rotation={[0, Math.PI / 2, 0]}
			/>
			<mesh
				geometry={nodes.Object_68.geometry}
				material={materials.details}
				position={[2.268, -0.206, 0.052]}
				rotation={[0, 0, -Math.PI / 2]}
			/>
			<mesh
				geometry={nodes.Object_70.geometry}
				material={materials.details}
				position={[2.268, -0.206, -0.282]}
				rotation={[0, 0, -Math.PI / 2]}
			/>
			<mesh geometry={nodes.Object_72.geometry} material={materials.details} />
			<mesh geometry={nodes.Object_74.geometry} material={materials.details} />
			<mesh
				geometry={nodes.Object_76.geometry}
				material={materials.details}
				position={[-3.175, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_78.geometry}
				material={materials.details}
				position={[1.87, 0.39, -0.76]}
			/>
			<mesh geometry={nodes.Object_80.geometry} material={materials.details} />
			<mesh
				geometry={nodes.Object_82.geometry}
				material={materials.details}
				position={[2.328, -0.205, -0.58]}
				rotation={[0, 0, 0.269]}
			/>
			<mesh geometry={nodes.Object_84.geometry} material={materials.details} />
			<mesh geometry={nodes.Object_86.geometry} material={materials.details} />
			<mesh
				geometry={nodes.Object_88.geometry}
				material={materials.keyboard}
				position={[1.853, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_90.geometry}
				material={materials.keyboard}
				position={[1.853, 0.348, 0.114]}
			/>
			<mesh
				geometry={nodes.Object_92.geometry}
				material={materials.keyboard}
				position={[1.853, 0.315, 0.303]}
			/>
			<mesh
				geometry={nodes.Object_94.geometry}
				material={materials.keyboard}
				position={[1.853, 0.275, 0.5]}
			/>
			<mesh
				geometry={nodes.Object_96.geometry}
				material={materials.keyboard}
				position={[1.262, 0.124, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_98.geometry}
				material={materials.keyboard}
				position={[1.153, 0.152, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_100.geometry}
				material={materials.keyboard}
				position={[1.252, 0.18, 0.118]}
			/>
			<mesh
				geometry={nodes.Object_102.geometry}
				material={materials.keyboard}
				position={[1.315, 0.209, -0.077]}
			/>
			<mesh
				geometry={nodes.Object_104.geometry}
				material={materials.keyboard}
				position={[1.089, 0.209, -0.077]}
			/>
			<mesh
				geometry={nodes.Object_106.geometry}
				material={materials.keyboard}
				position={[0.859, 0.208, -0.077]}
			/>
			<mesh
				geometry={nodes.Object_108.geometry}
				material={materials.keyboard}
				position={[0.632, 0.208, -0.077]}
			/>
			<mesh
				geometry={nodes.Object_110.geometry}
				material={materials.keyboard}
				position={[0.404, 0.208, -0.077]}
			/>
			<mesh
				geometry={nodes.Object_112.geometry}
				material={materials.keyboard}
				position={[0.175, 0.208, -0.077]}
			/>
			<mesh
				geometry={nodes.Object_114.geometry}
				material={materials.keyboard}
				position={[-0.052, 0.208, -0.077]}
			/>
			<mesh
				geometry={nodes.Object_116.geometry}
				material={materials.keyboard}
				position={[-0.279, 0.207, -0.077]}
			/>
			<mesh
				geometry={nodes.Object_118.geometry}
				material={materials.keyboard}
				position={[-0.51, 0.207, -0.077]}
			/>
			<mesh
				geometry={nodes.Object_120.geometry}
				material={materials.keyboard}
				position={[-0.735, 0.207, -0.078]}
			/>
			<mesh
				geometry={nodes.Object_122.geometry}
				material={materials.keyboard}
				position={[-0.965, 0.207, -0.078]}
			/>
			<mesh
				geometry={nodes.Object_124.geometry}
				material={materials.keyboard}
				position={[-1.193, 0.207, -0.078]}
			/>
			<mesh
				geometry={nodes.Object_126.geometry}
				material={materials.keyboard}
				position={[-1.42, 0.207, -0.078]}
			/>
			<mesh
				geometry={nodes.Object_128.geometry}
				material={materials.keyboard}
				position={[-1.648, 0.206, -0.078]}
			/>
			<mesh
				geometry={nodes.Object_130.geometry}
				material={materials.keyboard}
				position={[-1.875, 0.206, -0.078]}
			/>
			<mesh
				geometry={nodes.Object_132.geometry}
				material={materials.keyboard}
				position={[-2.102, 0.206, -0.078]}
			/>
			<mesh
				geometry={nodes.Object_134.geometry}
				material={materials.keyboard}
				position={[0.975, 0.18, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_136.geometry}
				material={materials.keyboard}
				position={[0.749, 0.18, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_138.geometry}
				material={materials.keyboard}
				position={[0.523, 0.18, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_140.geometry}
				material={materials.keyboard}
				position={[0.296, 0.179, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_142.geometry}
				material={materials.keyboard}
				position={[0.067, 0.179, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_144.geometry}
				material={materials.keyboard}
				position={[-0.159, 0.179, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_146.geometry}
				material={materials.keyboard}
				position={[-0.387, 0.179, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_148.geometry}
				material={materials.keyboard}
				position={[-0.61, 0.179, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_150.geometry}
				material={materials.keyboard}
				position={[-0.84, 0.178, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_152.geometry}
				material={materials.keyboard}
				position={[-1.064, 0.178, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_154.geometry}
				material={materials.keyboard}
				position={[-1.289, 0.178, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_156.geometry}
				material={materials.keyboard}
				position={[-1.518, 0.178, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_158.geometry}
				material={materials.keyboard}
				position={[-1.744, 0.178, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_160.geometry}
				material={materials.keyboard}
				position={[-2.05, 0.177, 0.116]}
			/>
			<mesh
				geometry={nodes.Object_162.geometry}
				material={materials.keyboard}
				position={[0.798, 0.151, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_164.geometry}
				material={materials.keyboard}
				position={[0.571, 0.151, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_166.geometry}
				material={materials.keyboard}
				position={[0.345, 0.151, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_168.geometry}
				material={materials.keyboard}
				position={[0.12, 0.151, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_170.geometry}
				material={materials.keyboard}
				position={[-0.108, 0.151, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_172.geometry}
				material={materials.keyboard}
				position={[-0.334, 0.15, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_174.geometry}
				material={materials.keyboard}
				position={[-0.56, 0.15, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_176.geometry}
				material={materials.keyboard}
				position={[-0.787, 0.15, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_178.geometry}
				material={materials.keyboard}
				position={[-1.014, 0.15, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_180.geometry}
				material={materials.keyboard}
				position={[-1.241, 0.15, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_182.geometry}
				material={materials.keyboard}
				position={[-1.467, 0.149, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_184.geometry}
				material={materials.keyboard}
				position={[-1.692, 0.149, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_186.geometry}
				material={materials.keyboard}
				position={[-1.92, 0.149, 0.307]}
			/>
			<mesh
				geometry={nodes.Object_188.geometry}
				material={materials.keyboard}
				position={[-2.145, 0.149, 0.307]}
			/>
			<mesh
				geometry={nodes.Object_190.geometry}
				material={materials.keyboard}
				position={[1.034, 0.123, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_192.geometry}
				material={materials.keyboard}
				position={[0.743, 0.123, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_194.geometry}
				material={materials.keyboard}
				position={[0.453, 0.123, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_196.geometry}
				material={materials.keyboard}
				position={[0.228, 0.123, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_198.geometry}
				material={materials.keyboard}
				position={[0.003, 0.123, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_200.geometry}
				material={materials.keyboard}
				position={[-0.224, 0.122, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_202.geometry}
				material={materials.keyboard}
				position={[-0.452, 0.122, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_204.geometry}
				material={materials.keyboard}
				position={[-0.678, 0.122, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_206.geometry}
				material={materials.keyboard}
				position={[-0.903, 0.122, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_208.geometry}
				material={materials.keyboard}
				position={[-1.13, 0.122, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_210.geometry}
				material={materials.keyboard}
				position={[-1.357, 0.121, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_212.geometry}
				material={materials.keyboard}
				position={[-1.584, 0.121, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_214.geometry}
				material={materials.keyboard}
				position={[-1.861, 0.121, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_216.geometry}
				material={materials.keyboard}
				position={[-2.143, 0.121, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_218.geometry}
				material={materials.keyboard}
				position={[1.853, 0.209, -0.077]}
			/>
			<mesh
				geometry={nodes.Object_220.geometry}
				material={materials.keyboard}
				position={[1.853, 0.124, 0.497]}
			/>
			<mesh
				geometry={nodes.Object_222.geometry}
				material={materials.keyboard}
				position={[1.853, 0.152, 0.308]}
			/>
			<mesh
				geometry={nodes.Object_224.geometry}
				material={materials.keyboard}
				position={[1.853, 0.18, 0.118]}
			/>
			<mesh
				geometry={nodes.Object_226.geometry}
				material={materials.keyboard}
				position={[-0.595, 0.119, 0.519]}
			/>
			<mesh
				geometry={nodes.Object_228.geometry}
				material={materials.keyboard}
				position={[-0.591, 0.241, 0.697]}
			/>
			<mesh
				geometry={nodes.Object_230.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_232.geometry}
				material={materials.keyboard}
				position={[1.261, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_234.geometry}
				material={materials.keyboard}
				position={[-2.132, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_236.geometry}
				material={materials.keyboard}
				position={[1.258, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_238.geometry}
				material={materials.keyboard}
				position={[1.152, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_240.geometry}
				material={materials.keyboard}
				position={[-2.032, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_242.geometry}
				material={materials.keyboard}
				position={[0.743, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_244.geometry}
				material={materials.keyboard}
				position={[-1.84, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_246.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_248.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_250.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_252.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_254.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_256.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_258.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_260.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_262.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_264.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_266.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_268.geometry}
				material={materials.keyboard}
				position={[0.974, 0.341, 0.121]}
			/>
			<mesh
				geometry={nodes.Object_270.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_272.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_274.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_276.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_278.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_280.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_282.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_284.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_286.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_288.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_290.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_292.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_294.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_296.geometry}
				material={materials.keyboard}
				position={[0.806, 0.307, 0.313]}
			/>
			<mesh
				geometry={nodes.Object_298.geometry}
				material={materials.keyboard}
				position={[1.261, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_300.geometry}
				material={materials.keyboard}
				position={[0.453, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_302.geometry}
				material={materials.keyboard}
				position={[0.453, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_304.geometry}
				material={materials.keyboard}
				position={[0.453, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_306.geometry}
				material={materials.keyboard}
				position={[0.453, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_308.geometry}
				material={materials.keyboard}
				position={[0.453, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_310.geometry}
				material={materials.keyboard}
				position={[0.453, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_312.geometry}
				material={materials.keyboard}
				position={[0.453, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_314.geometry}
				material={materials.keyboard}
				position={[0.453, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_316.geometry}
				material={materials.keyboard}
				position={[0.453, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_318.geometry}
				material={materials.keyboard}
				position={[0.453, 0.275, 0.501]}
			/>
			<mesh
				geometry={nodes.Object_320.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_322.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_324.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_326.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_328.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_330.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_332.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_334.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_336.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_338.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_340.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_342.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_344.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_346.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_348.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh
				geometry={nodes.Object_350.geometry}
				material={materials.keyboard}
				position={[1.315, 0.375, -0.076]}
			/>
			<mesh geometry={nodes.Object_352.geometry} material={materials.main_body} />
			<mesh
				geometry={nodes.Object_354.geometry}
				material={materials.main_body}
				position={[0, 0, -0.023]}
			/>
			<mesh
				geometry={nodes.Object_356.geometry}
				material={materials.details}
				position={[1.423, -0.247, -0.882]}
			/>
			<mesh
				geometry={nodes.Object_358.geometry}
				material={materials.details}
				position={[1.423, -0.247, -0.882]}
			/>
			<mesh
				geometry={nodes.Object_360.geometry}
				material={materials.details}
				position={[1.423, -0.299, -1.124]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_362.geometry}
				material={materials.details}
				position={[-1.465, -0.299, -1.1]}
			/>
			<mesh
				geometry={nodes.Object_364.geometry}
				material={materials.details}
				position={[-1.465, -0.299, -0.703]}
			/>
			<mesh
				geometry={nodes.Object_366.geometry}
				material={materials.details}
				position={[0.555, -0.232, -1.03]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_368.geometry}
				material={materials.details}
				position={[1.423, -0.299, -1.124]}
			/>
			<mesh
				geometry={nodes.Object_370.geometry}
				material={materials.details}
				position={[1.423, -0.326, -0.921]}
			/>
			<mesh
				geometry={nodes.Object_372.geometry}
				material={materials.details}
				position={[-1.405, -0.299, -1.028]}
			/>
			<mesh
				geometry={nodes.Object_374.geometry}
				material={materials.details}
				position={[-1.681, -0.231, -0.908]}
			/>
			<mesh
				geometry={nodes.Object_376.geometry}
				material={materials.details}
				position={[-1.591, -0.276, -0.91]}
			/>
			<mesh
				geometry={nodes.Object_378.geometry}
				material={materials.details}
				position={[-0.992, -0.231, -0.908]}
			/>
			<mesh
				geometry={nodes.Object_380.geometry}
				material={materials.details}
				position={[-0.902, -0.276, -0.91]}
			/>
			<mesh
				geometry={nodes.Object_382.geometry}
				material={materials.details}
				position={[-2.025, -0.271, -0.81]}
				rotation={[0, -Math.PI / 2, 0]}
			/>
			<mesh
				geometry={nodes.Object_384.geometry}
				material={materials.details}
				position={[-2.025, -0.271, -0.75]}
				rotation={[0, -Math.PI / 2, 0]}
			/>
			<mesh
				geometry={nodes.Object_386.geometry}
				material={materials.details}
				position={[-2.025, -0.271, -0.689]}
				rotation={[0, -Math.PI / 2, 0]}
			/>
			<mesh
				geometry={nodes.Object_388.geometry}
				material={materials.details}
				position={[-2.025, -0.271, -0.629]}
				rotation={[0, -Math.PI / 2, 0]}
			/>
			<mesh
				geometry={nodes.Object_390.geometry}
				material={materials.details}
				position={[-1.534, -0.271, -0.768]}
				rotation={[0, -Math.PI / 2, 0]}
			/>
			<mesh
				geometry={nodes.Object_392.geometry}
				material={materials.details}
				position={[-1.534, -0.271, -0.708]}
				rotation={[0, -Math.PI / 2, 0]}
			/>
			<mesh
				geometry={nodes.Object_394.geometry}
				material={materials.details}
				position={[-1.11, -0.271, -0.768]}
				rotation={[0, -Math.PI / 2, 0]}
			/>
			<mesh
				geometry={nodes.Object_396.geometry}
				material={materials.details}
				position={[-1.11, -0.271, -0.708]}
				rotation={[0, -Math.PI / 2, 0]}
			/>
			<mesh
				geometry={nodes.Object_398.geometry}
				material={materials.details}
				position={[-1.859, -0.249, -0.75]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_400.geometry}
				material={materials.details}
				position={[-1.859, -0.249, -0.68]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_402.geometry}
				material={materials.details}
				position={[-1.738, -0.249, -0.75]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_404.geometry}
				material={materials.details}
				position={[-1.738, -0.249, -0.68]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_406.geometry}
				material={materials.details}
				position={[-0.977, -0.249, -0.75]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_408.geometry}
				material={materials.details}
				position={[-0.977, -0.249, -0.68]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_410.geometry}
				material={materials.details}
				position={[-0.801, -0.249, -0.75]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_412.geometry}
				material={materials.details}
				position={[-0.801, -0.249, -0.68]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_414.geometry}
				material={materials.details}
				position={[-2.139, -0.249, -0.912]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_416.geometry}
				material={materials.details}
				position={[-2.139, -0.249, -0.842]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_418.geometry}
				material={materials.details}
				position={[-2.139, -0.249, -0.771]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_420.geometry}
				material={materials.details}
				position={[-2.139, -0.249, -0.699]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Object_422.geometry}
				material={materials.details}
				position={[-2.139, -0.249, -0.628]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
		</group>
	)
}

useGLTF.preload('/scene.gltf')
